[project]
name = "advent"
requires-python = ">=3.14"

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = ["B", "C4", "E", "F", "I", "PERF", "SIM", "UP", "W"]
ignore = ["E203", "SIM115"]
